"""empty message

Revision ID: 55fec626ef6e
Revises: d233828718f7
Create Date: 2018-06-05 12:27:47.176938

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '55fec626ef6e'
down_revision = 'd233828718f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projet',
                    sa.Column('id_Projet', sa.Integer(), nullable=False),
                    sa.Column('nom', sa.String(length=30), nullable=True),
                    sa.Column('description_Projet', sa.Text(), nullable=True),
                    sa.Column('workflow_id_workflow', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['workflow_id_workflow'], ['workflow.id_Workflow'], ),
                    sa.PrimaryKeyConstraint('id_Projet')
                    )
    op.create_index(op.f('ix_projet_workflow_id_workflow'), 'projet', ['workflow_id_workflow'], unique=False)
    op.create_table('workflow',
                    sa.Column('id_Workflow', sa.Integer(), nullable=False),
                    sa.Column('nom', sa.String(length=30), nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('projet_id_projet', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['projet_id_projet'], ['projet.id_Projet'], ),
                    sa.PrimaryKeyConstraint('id_Workflow')
                    )
    op.create_index(op.f('ix_workflow_projet_id_projet'), 'workflow', ['projet_id_projet'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_projet_id_projet'), table_name='workflow')
    op.drop_table('workflow')
    op.drop_index(op.f('ix_projet_workflow_id_workflow'), table_name='projet')
    op.drop_table('projet')
    # ### end Alembic commands ###
