"""empty message

Revision ID: 74c8d95be868
Revises: ea76df970007
Create Date: 2018-06-05 15:11:00.231934

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74c8d95be868'
down_revision = 'ea76df970007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('utilisateurs')
    op.create_foreign_key(None, 'est_cree_user', 'utilisateur', ['id_Utilisateur'], ['id'])
    op.create_foreign_key(None, 'est_cree_user', 'projet', ['id_Projet'], ['id_Projet'])
    op.create_foreign_key(None, 'est_mene_user', 'utilisateur', ['id_Utilisateur'], ['id'])
    op.create_foreign_key(None, 'est_mene_user', 'projet', ['id_Projet'], ['id_Projet'])
    op.create_foreign_key(None, 'etape', 'workflow', ['id_Workflow'], ['id_Workflow'])
    op.create_foreign_key(None, 'etape', 'langage', ['id_Langage'], ['id_Langage'])
    op.create_foreign_key(None, 'projet', 'workflow', ['workflow_id_workflow'], ['id_Workflow'])
    op.create_foreign_key(None, 'variable_env', 'etape', ['id_Etape'], ['id_Etape'])
    op.create_foreign_key(None, 'workflow', 'projet', ['projet_id_projet'], ['id_Projet'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow', type_='foreignkey')
    op.drop_constraint(None, 'variable_env', type_='foreignkey')
    op.drop_constraint(None, 'projet', type_='foreignkey')
    op.drop_constraint(None, 'etape', type_='foreignkey')
    op.drop_constraint(None, 'etape', type_='foreignkey')
    op.drop_constraint(None, 'est_mene_user', type_='foreignkey')
    op.drop_constraint(None, 'est_mene_user', type_='foreignkey')
    op.drop_constraint(None, 'est_cree_user', type_='foreignkey')
    op.drop_constraint(None, 'est_cree_user', type_='foreignkey')
    op.create_table('utilisateurs',
                    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
                    sa.Column('username', mysql.VARCHAR(length=30), nullable=False),
                    sa.Column('firstname', mysql.VARCHAR(length=30), nullable=False),
                    sa.Column('lastname', mysql.VARCHAR(length=30), nullable=False),
                    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
                    sa.Column('email', mysql.VARCHAR(length=30), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_default_charset='latin1',
                    mysql_engine='MyISAM'
                    )
    # ### end Alembic commands ###
