"""empty message

Revision ID: c9eb00187977
Revises: 74c8d95be868
Create Date: 2018-06-11 15:41:16.214796

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c9eb00187977'
down_revision = '74c8d95be868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workflow_projet_id_projet', table_name='workflow')
    op.drop_table('workflow')
    op.create_foreign_key(None, 'est_cree_user', 'projet', ['id_Projet'], ['id_Projet'])
    op.create_foreign_key(None, 'est_cree_user', 'utilisateur', ['id_Utilisateur'], ['id'])
    op.create_foreign_key(None, 'est_mene_user', 'utilisateur', ['id_Utilisateur'], ['id'])
    op.create_foreign_key(None, 'est_mene_user', 'projet', ['id_Projet'], ['id_Projet'])
    op.add_column('etape', sa.Column('id_Projet', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_etape_id_Projet'), 'etape', ['id_Projet'], unique=False)
    op.drop_index('ix_etape_id_Workflow', table_name='etape')
    op.create_foreign_key(None, 'etape', 'langage', ['id_Langage'], ['id_Langage'])
    op.create_foreign_key(None, 'etape', 'projet', ['id_Projet'], ['id_Projet'])
    op.drop_column('etape', 'id_Workflow')
    op.drop_index('ix_projet_workflow_id_workflow', table_name='projet')
    op.drop_column('projet', 'workflow_id_workflow')
    op.create_foreign_key(None, 'variable_env', 'etape', ['id_Etape'], ['id_Etape'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'variable_env', type_='foreignkey')
    op.add_column('projet', sa.Column('workflow_id_workflow', mysql.INTEGER(display_width=11), autoincrement=False,
                                      nullable=True))
    op.create_index('ix_projet_workflow_id_workflow', 'projet', ['workflow_id_workflow'], unique=False)
    op.add_column('etape',
                  sa.Column('id_Workflow', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'etape', type_='foreignkey')
    op.drop_constraint(None, 'etape', type_='foreignkey')
    op.create_index('ix_etape_id_Workflow', 'etape', ['id_Workflow'], unique=False)
    op.drop_index(op.f('ix_etape_id_Projet'), table_name='etape')
    op.drop_column('etape', 'id_Projet')
    op.drop_constraint(None, 'est_mene_user', type_='foreignkey')
    op.drop_constraint(None, 'est_mene_user', type_='foreignkey')
    op.drop_constraint(None, 'est_cree_user', type_='foreignkey')
    op.drop_constraint(None, 'est_cree_user', type_='foreignkey')
    op.create_table('workflow',
                    sa.Column('id_Workflow', mysql.INTEGER(display_width=11), nullable=False),
                    sa.Column('nom', mysql.VARCHAR(length=30), nullable=True),
                    sa.Column('description', mysql.TEXT(), nullable=True),
                    sa.Column('projet_id_projet', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id_Workflow'),
                    mysql_default_charset='latin1',
                    mysql_engine='MyISAM'
                    )
    op.create_index('ix_workflow_projet_id_projet', 'workflow', ['projet_id_projet'], unique=False)
    # ### end Alembic commands ###
