"""empty message

Revision ID: d233828718f7
Revises: 
Create Date: 2018-06-05 11:41:41.497138

"""
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd233828718f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('utilisateur', 'email',
                    existing_type=mysql.VARCHAR(length=30),
                    nullable=True)
    op.alter_column('utilisateur', 'firstname',
                    existing_type=mysql.VARCHAR(length=30),
                    nullable=True)
    op.alter_column('utilisateur', 'lastname',
                    existing_type=mysql.VARCHAR(length=30),
                    nullable=True)
    op.alter_column('utilisateur', 'password',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=True)
    op.alter_column('utilisateur', 'username',
                    existing_type=mysql.VARCHAR(length=30),
                    nullable=True)
    op.create_unique_constraint(None, 'utilisateur', ['email'])
    op.create_unique_constraint(None, 'utilisateur', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'utilisateur', type_='unique')
    op.drop_constraint(None, 'utilisateur', type_='unique')
    op.alter_column('utilisateur', 'username',
                    existing_type=mysql.VARCHAR(length=30),
                    nullable=False)
    op.alter_column('utilisateur', 'password',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('utilisateur', 'lastname',
                    existing_type=mysql.VARCHAR(length=30),
                    nullable=False)
    op.alter_column('utilisateur', 'firstname',
                    existing_type=mysql.VARCHAR(length=30),
                    nullable=False)
    op.alter_column('utilisateur', 'email',
                    existing_type=mysql.VARCHAR(length=30),
                    nullable=False)
    # ### end Alembic commands ###
